### ISSUE TITLE
Change path to app-bundle.js in vendor-bundle.js

### ISSUE THREAD

**Issue by radenkozec** [aurelia/bootstrapper-webpack#11]
**I'm submitting a bug report**
- **Library Version:**
  Aurelia 1.0.0

**Please tell us about your environment:**
- **Operating System:**
  Windows [10]
- **Node Version:**
  4.4.7
- **NPM Version:**
  3.10.6
- **Webpack**
- **Language:**
  ESNext

**Current behavior:**
I am using Webpack with CLI on ASP.NET Core project.
I am using CLI for build and run project via Visual Studio.
Everything works fine if I go to http://localhost:9000/index.html and Aurelia Hello World is loaded.

When I try to use Aurelia from ASP.NET MVC View using problems occur.
My code in ASP.NET MVC View looks like this:
`<div aurelia-app="main">
    <script src="~/scripts/vendor-bundle.js" data-main="aurelia-bootstrapper"></script>
</div>`

I have changed path to vendor-bundle.js to point to **wwwRoot folder**
When I try to load view path to app-bundle.js still looking for Home/script/app-bundle.js instead of looking in wwwRoot folder.
It seams that path of app-bundle.js is **hardcoded** in vendor-bundle.js file.
Is there a way to configure it inside aurelia.json or somewhere to look into wwwRoot folder?

**Comment by niieani** [comment]
You need to configure the output path in Webpack if you want to use a subdirectory.
Note that your combination of tooling is not yet officially supported.

**Comment by radenkozec** [comment]
@niieani Can you please to give me clue how to configure output path in Webpack. I am not familiar with Webpack configuration.

**Comment by niieani** [comment]
If you're using configs provided in the skeletons, see this line of code: https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-esnext-webpack/webpack.config.js#L16.

**Comment by radenkozec** [comment]
@niieani I have copied your webpack.config into root of my project. Changed line you suggested and then build project using CLI au build. Nothing happens.
Path in vendor-bundle.js still remains like `"app-bundle":"../scripts/app-bundle"`
Not sure if CLI uses this new copied config?

**Comment by niieani** [comment]
CLI does not support Webpack yet, so not sure what would that accomplish.
