### ISSUE TITLE
Bootstrapper crashes webpack build

### ISSUE THREAD

**Issue by peterver** [aurelia/bootstrapper-webpack#14]
**I'm submitting a bug report**

* **Library Version:**
1.1.0

**Please tell us about your environment:**

* **Operating System:**
OSX 10.12.3 Beta (16D17a)

* **Node Version:**
7.2.0

* **NPM Version:**
3.10.9

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.27

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
Running a webpack build fails due to the webpack-loader parsing all node_modules instead of only the required ones

**Expected/desired behavior:**
Bumping the aurelia-loader-webpack version to 2.x.x

Bootstrapper should one use the requested dependencies instead of all packages inside of node_modules

* **What is the motivation / use case for changing the behavior?**
Bootstrapper is targetting/parsing files it shouldn't, in projects where the repo is not solely dedicated to the aurelia app this forms an issue.

**Comment by peterver** [comment]
I know this is me commenting on my own pr, but i can confirm that #15 fixes the issue at hand

**Comment by niieani** [comment]
See comment on #15.

**Comment by EisenbergEffect** [comment]
@niieani Can this be closed?
