### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by niieani** [aurelia/bootstrapper-webpack#17]
@EisenbergEffect We should probably deprecate this package and ask everyone to use the `bootstrapper` once we the release the stable version of webpack-plugin@2.0.0.

**Comment by EisenbergEffect** [comment]
Makes sense.

**Comment by atoninelli** [comment]
Please could you specify which (and how) package to use instead. Possibly with github links, thanks.

**Comment by jods4** [comment]
@atoninelli When using the new Webpack 2.0 plugins (currently stable albeit in RC status), the regular `aurelia-bootstrapper` should be used. There's no need for this special library anymore.

**Comment by Alexander-Taran** [comment]
@bigopon can be closed
