### ISSUE TITLE
Promise is undefined in IE11

### ISSUE THREAD

**Issue by devcube** [aurelia/bootstrapper-webpack#3]
Hi,

When using Internet Explorer 11 I get this error:

```
SCRIPT5009: 'Promise' is undefined
aurelia-bootstrapper-webpack.js (33,3)
```

This does not happen on Chrome or Edge (I haven't tried other browsers). This repo uses Promise but the aurelia-polyfills package does not seem to have a Promise export.
The fix could be super simple, I'm just not experienced in this world yet :)

Thanks for the aurelia webpack support, it is awesome!

**Comment by EisenbergEffect** [comment]
I would recommend adding bluebird to handle promises.

**Comment by EisenbergEffect** [comment]
If the loader you are using does not include a Promise polyfill, you will need to include one yourself. We recommend Bluebird.

**Comment by devcube** [comment]
Thanks @EisenbergEffect, I got it working and also created a PR if you want to add it to the main repo.
