### ISSUE TITLE
Secondary node_modules folder under aurelia-bootstrapper-webpack folder

### ISSUE THREAD

**Issue by jsobell** [aurelia/bootstrapper-webpack#5]
The `npm install` process is currently adding an additional nested `node_modules` folder containing aurelia-loader-webpack under the `node_modules/aurelia-bootstrapper-webpack` folder.
Result;
`./node_modules/aurelia-bootstrapper-webpack/node_modules/aurelia-loader-webpack/[loader files]`

**Comment by EisenbergEffect** [comment]
You need to be using npm 3 or run the dedupe. See the webpack skeleton for instructions.
