### ISSUE TITLE
Safari - RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by jkehler** [aurelia/bootstrapper-webpack#9]
When trying to test my application in Safari I am getting RangeError: Maximum call stack size exceeded. error and the app won't boot. However the app works fine in Chrome.

I narrowed it down to this module by completely removing the initialization of Aurelia and having my main.js file only import aurelia-bootstrapper-webpack. Just importing this module will cause the error above to happen.

The stack trace points to the following block of code in my bundle.js.

```
            function createCollection(proto, objectOnly) {
                function Collection(a) {
                    if (!this || this.constructor !== Collection) 
                        return new Collection(a);
                    this._keys = [];
                    this._values = [];
                    this._itp = [];
                    this.objectOnly = objectOnly;

                    if (a) 
                        init.call(this, a);
                }
```

**Comment by EisenbergEffect** [comment]
We've got new official webpack setups now. Perhaps there was a configuration issue. We haven't been able to reproduce this issue.
